import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceFiles = [
  'data.js',
  'dom.js',
  'timeline-model.js',
  'cooldowns.js',
  'selection.js',
  'resources.js',
  'availability.js',
  'rendering.js',
  'commands.js',
  'persistence.js',
  'bootstrap.js'
];

const banner = '// Generated by scripts/build.mjs from src/*.js. Edit src files, then run npm run build.\n\n';

const chunks = await Promise.all(sourceFiles.map(async file => {
  const content = await readFile(path.join(root, 'src', file), 'utf8');
  return `// --- src/${file} ---\n${content.trimEnd()}\n`;
}));

await writeFile(path.join(root, 'app.js'), banner + chunks.join('\n'), 'utf8');

const syntaxCheck = spawnSync(process.execPath, ['--check', path.join(root, 'app.js')], { stdio: 'inherit' });
if (syntaxCheck.status !== 0) process.exit(syntaxCheck.status ?? 1);

await mkdir(path.join(root, 'dist'), { recursive: true });
await Promise.all([
  copyFile(path.join(root, 'index.html'), path.join(root, 'dist', 'index.html')),
  copyFile(path.join(root, 'app.js'), path.join(root, 'dist', 'app.js')),
  copyFile(path.join(root, 'styles.css'), path.join(root, 'dist', 'styles.css'))
]);
